name = "pdf2md"
main = "src/index.tsx"
compatibility_date = "2025-06-14"
minify = true
upload_source_maps = true
workers_dev = false
preview_urls = false

[assets]
directory = "./public/"

[observability]
enabled = true

[ai]
binding = "AI"
